---
title: "Analysis of the New York Housing Market"
format: html
---


```{r}

library(dplyr)
library(ggplot2)
library(plotly)
library(tidyr)
library(hexbin)
library(RColorBrewer)
library(forcats)
library(crosstalk)
library(ggiraph)

library(survey)

library(srvyr)

library(tidycensus)

library(sf)

library(jsonlite)

library(tigris)

library(stringr)

library(leaflet)
library(htmlwidgets)
library(htmltools)
library(gt)
library(DT)


```




# Review


```{r}


saveRDS(ny_housing, "ny_housing.rds")


```


```{r}


ny_housing<-readRDS("ny_housing.rds")

```



```{r}



ny_housing |> glimpse()


```



```{r}



ny_housing |> summary()


```



```{r}

ny_housing |> 
    select(STATE, MAIN_ADDRESS, FORMATTED_ADDRESS, LOCALITY) |> 
    head(20)


```




The address fields are not consistant on the city or town names.  In some instances the city name is actually a neighborhood within a city or New York City borough. 

We will use the stringr package and regular expressions to extract the zip code which then can be used to determine the city. 





```{r}


ny_housing_2<-ny_housing |> 
    mutate(zip_cde=str_extract(MAIN_ADDRESS,"\\d{5}"))




```


```{r}


ny_housing_2 |> 
    select(zip_cde) |> 
    head(20)



```




```{r}


glimpse(ny_housing_2)


```






```{r}

ny_housing_2 |> 
    select(zip_cde) |> 
    head(20)


```


```{r}


saveRDS(ny_housing_2,"ny_housing_2.rds")


```















```{r}






```





```{r}






```





# Cenus







```{r}



Sys.getenv("CENSUS_API_KEY")

```



```{r}



census_2020<-load_variables(2020,"pl",cache=TRUE)


```





```{r}


acs_5 <- load_variables(2024,"acs5", cache = TRUE)



```


```{r}


median_age <- get_acs(
    geography = "state",
    variables = "B01002_001",
    year=2024
)



```



```{r}


load_variables(2020,"acs5")



```